server.port=8084
spring.application.name=ms-analiticas

spring.datasource.url=jdbc:mysql://localhost:3306/innovatech_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
